"use client";

import { FormEvent, useMemo, useState } from "react";

type Lead = { id: string; public_number: number; name: string; phone: string; message: string | null; source: string; status: string; assigned_telegram_name: string | null; created_at: string };
type Comment = { id: number; lead_id: string; body: string; author_name: string; created_at: string };
const labels: Record<string, string> = { new: "Новая", in_progress: "В работе", contacted: "Связались", quote_sent: "Расчёт отправлен", waiting: "Ожидание", won: "Успешно", lost: "Отказ" };

export function LeadsDashboard({ leads: initialLeads, comments: initialComments }: { leads: Lead[]; comments: Comment[] }) {
  const [leads, setLeads] = useState(initialLeads); const [comments, setComments] = useState(initialComments); const [status, setStatus] = useState("all"); const [activeId, setActiveId] = useState(initialLeads[0]?.id ?? "");
  const active = leads.find((lead) => lead.id === activeId); const visible = useMemo(() => status === "all" ? leads : leads.filter((lead) => lead.status === status), [leads, status]);
  const updateStatus = async (next: string) => { if (!active) return; const response = await fetch(`/api/admin/leads/${active.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: next }) }); if (response.ok) setLeads((items) => items.map((item) => item.id === active.id ? { ...item, status: next } : item)); };
  const addComment = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!active) return; const form = event.currentTarget; const body = String(new FormData(form).get("body") ?? ""); const response = await fetch(`/api/admin/leads/${active.id}/comments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body }) }); if (response.ok) { setComments((items) => [...items, { id: Date.now(), lead_id: active.id, body, author_name: "Администратор", created_at: new Date().toISOString() }]); form.reset(); } };
  return <main className="admin-shell"><header className="admin-header"><div><p>Честный пригон</p><h1>Заявки</h1></div><span>{leads.length} всего</span></header><div className="admin-filters"><button className={status === "all" ? "is-active" : ""} onClick={() => setStatus("all")}>Все</button>{Object.entries(labels).map(([key, label]) => <button key={key} className={status === key ? "is-active" : ""} onClick={() => setStatus(key)}>{label}</button>)}</div><section className="admin-workspace"><aside className="admin-lead-list">{visible.map((lead) => <button key={lead.id} className={lead.id === activeId ? "is-active" : ""} onClick={() => setActiveId(lead.id)}><span>#{lead.public_number} · {labels[lead.status]}</span><b>{lead.name}</b><small>{lead.phone} · {new Intl.DateTimeFormat("ru-RU", { dateStyle: "short", timeStyle: "short" }).format(new Date(lead.created_at))}</small></button>)}{!visible.length ? <p>Заявок нет.</p> : null}</aside>{active ? <article className="admin-lead-detail"><div className="admin-lead-top"><div><span>Заявка #{active.public_number}</span><h2>{active.name}</h2><a href={`tel:${active.phone}`}>{active.phone}</a></div><select value={active.status} onChange={(event) => void updateStatus(event.target.value)}>{Object.entries(labels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div><dl><div><dt>Источник</dt><dd>{active.source}</dd></div><div><dt>Ответственный</dt><dd>{active.assigned_telegram_name ?? "Не назначен"}</dd></div><div><dt>Комментарий клиента</dt><dd>{active.message ?? "—"}</dd></div></dl><section className="admin-comments"><h3>Комментарии</h3>{comments.filter((item) => item.lead_id === active.id).map((item) => <div key={item.id}><b>{item.author_name}</b><span>{item.body}</span></div>)}<form onSubmit={addComment}><textarea name="body" placeholder="Добавить комментарий" required /><button>Сохранить</button></form></section></article> : <article className="admin-lead-detail"><p>Выберите заявку.</p></article>}</section></main>;
}
